"""Add reddit_posts table

Revision ID: c0e264bceb0e
Revises: 859ecbd826dd
Create Date: 2026-09-18 00:23:18.117253

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0e264bceb0e'
down_revision = '859ecbd826dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reddit_posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.String(length=20), nullable=False),
    sa.Column('subreddit', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('author', sa.String(length=100), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('num_comments', sa.Integer(), nullable=True),
    sa.Column('posted_at', sa.DateTime(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('post_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reddit_posts')
    # ### end Alembic commands ###
